spring:
  application:
    name: eureka-server-2
#---
#server:
#  port: 8761
##指定profile=peer1
#  profiles: peer1
#eureka:
#  instance:
##指定当profiles = peer1时，主机是peer1
#    hostname: peer1
#  client:
#    service-url:
#    #将自身注册到peer2
#      defaultZone: http://localhost:8762/eureka/
#
#---
server:
  port: 8762
#指定profile=peer2
  profiles: peer2
eureka:
  instance:
#指定当profiles = peer2时，主机是peer2
    hostname: peer2
  client:
    service-url:
    #将自身注册到peer1
      defaultZone: http://localhost:8764/eureka/
      



